# Generated by Django 4.2.3 on 2023-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='display',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='display',
            name='date',
            field=models.DateField(verbose_name='Display Date'),
        ),
        migrations.AddField(
            model_name='art',
            name='museums',
            field=models.ManyToManyField(to='main_app.museum'),
        ),
    ]
